name: Trigger auto deployment for expense-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/expense-backend-AutoDeployTrigger-3c185d51-e302-4ade-936a-ee125866cf4d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EXPENSEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EXPENSEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EXPENSEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: expensetrackeracr2026.azurecr.io
          registryUsername: ${{ secrets.EXPENSEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EXPENSEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: expense-backend
          resourceGroup: rg-expenset-prod
          imageToBuild: expensetrackeracr2026.azurecr.io/expense-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


